import { registerEmployeeTools } from "./tools/employeeTools.js";
import { registerAttendanceTools } from "./tools/attendanceTools.js";
import { registerLeaveTools } from "./tools/leaveTools.js";
import { registerPayrollTools } from "./tools/payrollTools.js";
import { registerPerformanceTools } from "./tools/performanceTools.js";
import { registerRecruitmentTools } from "./tools/recruitmentTools.js";
import { registerOnboardingTools } from "./tools/onboardingTools.js";
import { registerLearningTools } from "./tools/learningTools.js";
import { registerComplianceTools } from "./tools/complianceTools.js";
import { registerBenefitTools } from "./tools/benefitTools.js";
import { registerAnalyticsTools } from "./tools/analyticsTools.js";
import { registerSelfTools } from "./tools/selfTools.js";
import { registerResumeTools } from "./tools/resumeTools.js";
import { registerOrgChartTools } from "./tools/orgChartTools.js";
import { registerPositionMgmtTools } from "./tools/positionMgmtTools.js";
import { registerProfileActionTools } from "./tools/profileActionTools.js";
import { registerRequisitionMgmtTools } from "./tools/requisitionMgmtTools.js";
import { registerCandidatePipelineTools } from "./tools/candidatePipelineTools.js";
import { registerInterviewMgmtTools } from "./tools/interviewMgmtTools.js";
import { registerOfferMgmtTools } from "./tools/offerMgmtTools.js";
import { registerTalentPoolMgmtTools } from "./tools/talentPoolMgmtTools.js";
import { registerRecruitmentAnalyticsTools } from "./tools/recruitmentAnalyticsTools.js";
import { registerOnboardingMgmtTools } from "./tools/onboardingMgmtTools.js";
import { registerRecruitmentExtraTools } from "./tools/recruitmentExtraTools.js";
import { registerOnboardingDashboardTools } from "./tools/onboardingDashboardTools.js";
import { registerOnboardingDetailTools } from "./tools/onboardingDetailTools.js";
import { registerOnboardingScheduleTools } from "./tools/onboardingScheduleTools.js";
import { registerOnboardingPortalTools } from "./tools/onboardingPortalTools.js";
import { registerTimeAttendanceTools } from "./tools/timeAttendanceTools.js";
import { registerLeaveManagementTools } from "./tools/leaveManagementTools.js";
import { registerOvertimeShiftTools } from "./tools/overtimeShiftTools.js";
import { registerOvertimeManagerTools } from "./tools/overtimeManagerTools.js";
import { registerShiftTemplateSwapTools } from "./tools/shiftTemplateSwapTools.js";

export function registerAllTools(server) {
  registerEmployeeTools(server);
  registerAttendanceTools(server);
  registerLeaveTools(server);
  registerPayrollTools(server);
  registerPerformanceTools(server);
  registerRecruitmentTools(server);
  registerOnboardingTools(server);
  registerLearningTools(server);
  registerComplianceTools(server);
  registerBenefitTools(server);
  registerAnalyticsTools(server);
  registerSelfTools(server);
  registerResumeTools(server);
  registerOrgChartTools(server);
  registerPositionMgmtTools(server);
  registerProfileActionTools(server);
  registerRequisitionMgmtTools(server);
  registerCandidatePipelineTools(server);
  registerInterviewMgmtTools(server);
  registerOfferMgmtTools(server);
  registerTalentPoolMgmtTools(server);
  registerRecruitmentAnalyticsTools(server);
  registerOnboardingMgmtTools(server);
  registerRecruitmentExtraTools(server);
  registerOnboardingDashboardTools(server);
  registerOnboardingDetailTools(server);
  registerOnboardingScheduleTools(server);
  registerOnboardingPortalTools(server);
  registerTimeAttendanceTools(server);
  registerLeaveManagementTools(server);
  registerOvertimeShiftTools(server);
  registerOvertimeManagerTools(server);
  registerShiftTemplateSwapTools(server);
}
